app/models/coins.py
from . import db 
from datetime import datetime 

class Coin(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    value = db.Column(db.String(20), nullable=False)
    date_added = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __init__(self, name, value, user_id):
        self.name = name
        self.value = value
        self.user_id = user_id

    def __repr__(self):
        return '<Coin %r>' % self.name

app/forms/coins.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField,IntegerField,SelectField
from wtforms.validators import DataRequired, ValidationError, Email, EqualTo, Length
from app.models.coins import Coin
import os
import json

abs = os.path.abspath('.')
path_file = os.path.join(abs, 'app\\helpers\\coins.json')
with open(path_file, 'r') as f:
    data = json.load(f)
names = []
for i in data:
    names.append(i['name'])
    
class AddForm(FlaskForm):
    name = SelectField('name',choices=names)
    value = StringField('Value', validators=[DataRequired()])
    submit = SubmitField('Add')

app/views/coin.py
from re import T
from app.models import db
from flask import render_template, flash, redirect, url_for, request, session, Blueprint
from flask_login import current_user,login_required
from app.models.users import User
from app.models.coins import Coin
from app.forms.coins import AddForm
import os
from app.helpers.json_tasks import Tasks


coins = Blueprint('coin', __name__)



@coins.route('/coin/add', methods=['GET', 'POST'])
@login_required
def add_coin():
    form = AddForm()
    if form.validate_on_submit():
        new_coin = Coin(name=form.name.data,value=form.value.data,user_id=current_user.id)
        db.session.add(new_coin)
        db.session.commit()
        flash('Vous avez ajouté une nouvelle monnaie')
        return redirect(url_for('coin.list_coins'))
    return render_template('coins/add_coins.html', form=form,title='Ajouter une nouvelle monnaie')
   
@coins.route('/coin')
@login_required
def list_coins():
        coins = Coin.query.filter_by(user_id=current_user.id).all()
        return render_template('coins/list_coins.html', coins=coins,title='Mes monnaies')

@coins.route('/coin/<int:coin_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_coin(coin_id):
    coin = Coin.query.get_or_404(coin_id)
    if coin.user_id == current_user.id:
        db.session.delete(coin)
        db.session.commit()
        flash('Vous avez supprimé une monnaie')
        return redirect(url_for('coin.list_coins'))
    else:
        flash('Vous n\'avez pas le droit de supprimer cette monnaie')
        return redirect(url_for('coin.list_coins'))

@coins.route('/coin/<int:coin_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_coin(coin_id):
    coin = Coin.query.get_or_404(coin_id)
    if coin.user_id == current_user.id:
        form = AddForm()
        if form.validate_on_submit():
            coin.name = form.name.data
            coin.value = form.value.data
            db.session.commit()
            flash('Vous avez modifié une monnaie')
            return redirect(url_for('coin.list_coins'))
    return render_template('coins/edit_coins.html',coin_id = coin.id, form=form,title='Modifier une monnaie')



@coins.route('/coin/<int:coin_id>/detail', methods=['GET', 'POST'])
@login_required
def detail_coin(coin_id):
    coin = Coin.query.get_or_404(coin_id)
    if coin.user_id == current_user.id:
        details = Tasks().get_by_name(coin.name)
        return render_template('coins/detail_coins.html',coin=details,title='Détails de la monnaie')
    else:
        return redirect(url_for('coin.list_coins'))

app/templates/coins/add_coins.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="container ">
    <div class="authe">
        <div>
            <form action="{{ url_for('coin.add_coin') }}" method="post">
                <div class="form-group">
                    {{form.csrf_token}}
                </div>
                <div class="form-group text-center">
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    {% for message in messages %}
                    {% if connect == 'no' %}
                    <div class="alert alert-danger">{{ message }}
                        <a href="{{url_for('auth.register')}}">aller a la page d'inscription</a>
                    </div>
                    {% else %}
                    <div class="alert alert-success">{{ message }}</div>
                    {% endif %}
                    {% endfor %}
                    {% endif %}
                    {% endwith %}
                    {{form.name}}
                    {{form.value}}
                    <br>
                    {{form.submit(class='btn btn-primary',value='ajouter')}}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/coins/detail_coins.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
    <div class="container ">
        {{coin.name}}
        {{coin.slug}}
  
    </div>
{% endblock %}

app/templates/coins/edit_coins.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="container ">
    <div class="authe">
        <div>
            <form action="{{ url_for('coin.edit_coin',coin_id = coin_id) }}" method="post">
                <div class="form-group">
                    {{form.csrf_token}}
                </div>
                <div class="form-group text-center">
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    {% for message in messages %}
                    {% if connect == 'no' %}
                    <div class="alert alert-danger">{{ message }}
                        <a href="{{url_for('auth.register')}}">aller a la page d'inscription</a>
                    </div>
                    {% else %}
                    <div class="alert alert-success">{{ message }}</div>
                    {% endif %}
                    {% endfor %}
                    {% endif %}
                    {% endwith %}
                    {{form.name}}
                    {{form.value}}
                    <br>
                    {{form.submit(class='btn btn-primary',value='modifier')}}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/coins/list_coins.html
{% extends "base.html" %}
{% block title %}{{titre}}{% endblock %}
{% block content %}
<div class="container ">
    <ul>
    {% for coin in coins %}
               <li><h1>
                   <a href="{{url_for('coin.detail_coin', coin_id=coin.id)}}">{{coin.name}}</a> : {{coin.value}} 
                   <a href="{{url_for('coin.delete_coin',coin_id = coin.id)}}" class="btn btn-danger">suprimer</a>
                   <a href="{{url_for('coin.edit_coin',coin_id = coin.id)}}" class="btn btn-success">modifier</a>
                </h1>
            </li> 
    {% endfor %}
</ul>
<a href="{{url_for('coin.add_coin')}}" class="btn btn-info">ajouter</a>
</div>
{% endblock %}