app/views/home.py
from flask import Blueprint, render_template
home = Blueprint('home', __name__)
from app.helpers.json_tasks import Tasks



@home.route('/')
def index():
   data = Tasks().get_all()
   return render_template('home/index.html', data=data) 

app/templates/_renderForm.html
{% macro render_field(field) -%}
<div class="form-group">
    {{ field.label }}
    {{ field(class='form-control',**kwargs) }}
    {% for error in field.errors %}
        <div class="alert alert-danger">{{ error }}</div>
    {% endfor %}
</div>
{%- endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
    crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/style.css')}}">
<title>{%block title%} {% endblock %} </title>
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico')}}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://kit.fontawesome.com/45e38e596f.js" crossorigin="anonymous"></script>

</head>
<body>
    <header>
        <nav class="sidebar " >
            <div class="hamburger-menu">
                <div class="line line-1"></div>
                <div class="line line-2"></div>
                <div class="line line-3"></div>
            </div>
            <ul class="nav-list">
                {%  if current_user.is_authenticated %}
                <li class="user-sidebar ">
                    <a href="">
                        <img class="sidebar-img" src="{{url_for('static' ,filename='images/favicon.png') }}" alt="">
                    </a> <div class="account-sidebar">
                        <h2>{{current_user.name}}</h2>
                    </div>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a href="{{url_for('home.index')}}" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="" class="nav-link">Actualité</a>
                </li>
                <li class="mt-1 d-flex justify-content-center">
                    {% if current_user.is_authenticated%}
                        <a href=""><i class="far fa-sign-out-alt ml-3 awsome awsome-side"></i></a>
                    {% else %}
                        <div class="col">
                            <div class=" text-center pb-4 pt-2">
                                <a href="{{url_for('auth.login')}}" class="ml-2 " style="color: white">connexion</a>  <a href="{{url_for('auth.register')}}" class="ml-2 btn btn-success">inscription</a>
                            </div>
                            <div class="text-center pt-4">
                                <a href=""><i class="fas fa-shopping-basket ml-3 awsome awsome-side"></i></a>
                            </div>
                        </div>
                    {% endif %}
                </li> </ul>
                <li id="switch">
                    <label class="switch">
                        <input class="dark" type="checkbox">
                        <span class="slider round"></span>
                    </label>
                </li>
        </nav>
    </header>
   

   
    
    {% block content %}
    {% endblock %}
</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{{url_for('static',filename='js/_navbar.js')}}"></script>
</html>